version: "3.8"

services:

  # ================= PRODUCT =================
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - product-db

  product-db:
    image: mongo
    container_name: product-db
    ports:
      - "27017:27017"

  # ================= ORDER =================
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - order-db

  order-db:
    image: mongo
    container_name: order-db
    ports:
      - "27018:27017"

  # ================= CUSTOMER =================
  customer-service:
    build: ./customer-service
    ports:
      - "3003:3003"
    depends_on:
      - customer-db

  customer-db:
    image: mongo
    container_name: customer-db
    ports:
      - "27019:27017"

  # ================= API GATEWAY =================
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - customer-service